name: C/C++ CI

on: 
  push:
    paths: [ 'code/cpp/**' ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd code/cpp && mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cd code/cpp && cmake --build build
    - name: test
      run: cd code/cpp/build && ctest --verbose

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd code/cpp && mkdir build && cd build && cmake ..
    - name: build
      run: cd code/cpp && cmake --build build --config Debug
    - name: test
      run: cd code/cpp/build && ctest -C Debug --verbose
