name: Java CI with Gradle

on:
  push:
    paths: [
      '.github/workflows/java.yaml',
      'code/java/**'
    ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x code/java/gradlew
      - name: Build with Gradle
        run: cd code/java && ./gradlew build
