name: Rust CI

on:
  push:
    paths: [ 'code/rust/**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Access Rust directory
        run: cd code/rust
      - uses: actions-rs/cargo@v1
        with:
          command: test
